// error handling

try{
    console.log(a);

}catch(err){
    console.log("something went wrong");
}